2013-10-20T12:39:39.074Z - error: uncaughtException: Cannot read property 'length' of undefined date=Sun Oct 20 2013 20:39:39 GMT+0800 (中国标准时间), pid=8608, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=78286848, heapTotal=63359488, heapUsed=36167616, loadavg=[0, 0, 0], uptime=189376.1516105, trace=[column=54, file=D:\6\node\fablab\routes\course_milestone_api.js, function=null, line=174, method=null, native=false, column=4, file=D:\6\node\fablab\model\student_plan_model.js, function=, line=101, method=null, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false, column=13, file=D:\6\node\fablab\node_modules\mongoose\lib\query.js, function=null, line=1833, method=null, native=false, column=11, file=D:\6\node\fablab\node_modules\mongoose\lib\document.js, function=model.Document.init, line=251, method=Document.init, native=false, column=10, file=D:\6\node\fablab\node_modules\mongoose\lib\query.js, function=completeOne, line=1831, method=null, native=false, column=11, file=D:\6\node\fablab\node_modules\mongoose\lib\query.js, function=null, line=1799, method=null, native=false], stack=[TypeError: Cannot read property 'length' of undefined,     at D:\6\node\fablab\routes\course_milestone_api.js:174:54,     at Promise.<anonymous> (D:\6\node\fablab\model\student_plan_model.js:101:4),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20),     at D:\6\node\fablab\node_modules\mongoose\lib\query.js:1833:13,     at model.Document.init (D:\6\node\fablab\node_modules\mongoose\lib\document.js:251:11),     at completeOne (D:\6\node\fablab\node_modules\mongoose\lib\query.js:1831:10),     at D:\6\node\fablab\node_modules\mongoose\lib\query.js:1799:11]
2013-10-20T13:49:22.281Z - error: uncaughtException: undefined is not a function date=Sun Oct 20 2013 21:49:22 GMT+0800 (中国标准时间), pid=7164, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=78225408, heapTotal=62327552, heapUsed=35486496, loadavg=[0, 0, 0], uptime=193559.3578762, trace=[column=7, file=D:\6\node\fablab\model\student_answer_model.js, function=, line=122, method=null, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false, column=15, file=D:\6\node\fablab\node_modules\mongoose\lib\promise.js, function=Promise.resolve, line=108, method=resolve, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false], stack=[TypeError: undefined is not a function,     at Promise.<anonymous> (D:\6\node\fablab\model\student_answer_model.js:122:7),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20),     at Promise.resolve (D:\6\node\fablab\node_modules\mongoose\lib\promise.js:108:15),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20)]
2013-10-21T09:54:11.278Z - error: uncaughtException: Cannot read property 'plan' of null date=Mon Oct 21 2013 17:54:11 GMT+0800 (中国标准时间), pid=6796, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=113770496, heapTotal=83986176, heapUsed=46869056, loadavg=[0, 0, 0], uptime=262189.8613163, trace=[column=59, file=D:\6\node\fablab\routes\course_milestone_api.js, function=null, line=179, method=null, native=false, column=4, file=D:\6\node\fablab\model\student_plan_model.js, function=, line=101, method=null, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false, column=30, file=D:\6\node\fablab\node_modules\mongoose\lib\query.js, function=null, line=1794, method=null, native=false, column=16, file=D:\6\node\fablab\node_modules\mongoose\lib\utils.js, function=null, line=414, method=null, native=false, column=5, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js, function=null, line=953, method=null, native=false, column=35, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js, function=null, line=683, method=null, native=false], stack=[TypeError: Cannot read property 'plan' of null,     at D:\6\node\fablab\routes\course_milestone_api.js:179:59,     at Promise.<anonymous> (D:\6\node\fablab\model\student_plan_model.js:101:4),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20),     at D:\6\node\fablab\node_modules\mongoose\lib\query.js:1794:30,     at D:\6\node\fablab\node_modules\mongoose\lib\utils.js:414:16,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js:953:5,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js:683:35]
2013-10-21T15:42:12.615Z - error: uncaughtException: Cannot read property 'plan' of null date=Mon Oct 21 2013 23:42:12 GMT+0800 (中国标准时间), pid=6608, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=97263616, heapTotal=73666816, heapUsed=41507072, loadavg=[0, 0, 0], uptime=283071.1956603, trace=[column=59, file=D:\6\node\fablab\routes\course_milestone_api.js, function=null, line=179, method=null, native=false, column=4, file=D:\6\node\fablab\model\student_plan_model.js, function=, line=101, method=null, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false, column=30, file=D:\6\node\fablab\node_modules\mongoose\lib\query.js, function=null, line=1794, method=null, native=false, column=16, file=D:\6\node\fablab\node_modules\mongoose\lib\utils.js, function=null, line=414, method=null, native=false, column=5, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js, function=null, line=953, method=null, native=false, column=35, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js, function=null, line=683, method=null, native=false], stack=[TypeError: Cannot read property 'plan' of null,     at D:\6\node\fablab\routes\course_milestone_api.js:179:59,     at Promise.<anonymous> (D:\6\node\fablab\model\student_plan_model.js:101:4),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20),     at D:\6\node\fablab\node_modules\mongoose\lib\query.js:1794:30,     at D:\6\node\fablab\node_modules\mongoose\lib\utils.js:414:16,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js:953:5,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js:683:35]
2013-10-21T16:08:08.381Z - error: uncaughtException: Cannot read property 'plan' of null date=Tue Oct 22 2013 00:08:08 GMT+0800 (中国标准时间), pid=6608, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=97910784, heapTotal=75730688, heapUsed=32101208, loadavg=[0, 0, 0], uptime=284626.9666453, trace=[column=59, file=D:\6\node\fablab\routes\course_milestone_api.js, function=null, line=179, method=null, native=false, column=4, file=D:\6\node\fablab\model\student_plan_model.js, function=, line=101, method=null, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false, column=30, file=D:\6\node\fablab\node_modules\mongoose\lib\query.js, function=null, line=1794, method=null, native=false, column=16, file=D:\6\node\fablab\node_modules\mongoose\lib\utils.js, function=null, line=414, method=null, native=false, column=5, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js, function=null, line=953, method=null, native=false, column=35, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js, function=null, line=683, method=null, native=false], stack=[TypeError: Cannot read property 'plan' of null,     at D:\6\node\fablab\routes\course_milestone_api.js:179:59,     at Promise.<anonymous> (D:\6\node\fablab\model\student_plan_model.js:101:4),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20),     at D:\6\node\fablab\node_modules\mongoose\lib\query.js:1794:30,     at D:\6\node\fablab\node_modules\mongoose\lib\utils.js:414:16,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js:953:5,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js:683:35]
2013-10-21T16:20:16.894Z - error: uncaughtException: Cannot read property 'plan' of null date=Tue Oct 22 2013 00:20:16 GMT+0800 (中国标准时间), pid=6608, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=98193408, heapTotal=75730688, heapUsed=34167120, loadavg=[0, 0, 0], uptime=285355.4783138, trace=[column=59, file=D:\6\node\fablab\routes\course_milestone_api.js, function=null, line=179, method=null, native=false, column=4, file=D:\6\node\fablab\model\student_plan_model.js, function=, line=101, method=null, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false, column=30, file=D:\6\node\fablab\node_modules\mongoose\lib\query.js, function=null, line=1794, method=null, native=false, column=16, file=D:\6\node\fablab\node_modules\mongoose\lib\utils.js, function=null, line=414, method=null, native=false, column=5, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js, function=null, line=953, method=null, native=false, column=35, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js, function=null, line=683, method=null, native=false], stack=[TypeError: Cannot read property 'plan' of null,     at D:\6\node\fablab\routes\course_milestone_api.js:179:59,     at Promise.<anonymous> (D:\6\node\fablab\model\student_plan_model.js:101:4),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20),     at D:\6\node\fablab\node_modules\mongoose\lib\query.js:1794:30,     at D:\6\node\fablab\node_modules\mongoose\lib\utils.js:414:16,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js:953:5,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js:683:35]
2013-10-21T16:21:49.735Z - error: uncaughtException: Cannot read property 'plan' of null date=Tue Oct 22 2013 00:21:49 GMT+0800 (中国标准时间), pid=6608, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=98254848, heapTotal=75730688, heapUsed=31746312, loadavg=[0, 0, 0], uptime=285448.320624, trace=[column=59, file=D:\6\node\fablab\routes\course_milestone_api.js, function=null, line=179, method=null, native=false, column=4, file=D:\6\node\fablab\model\student_plan_model.js, function=, line=101, method=null, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false, column=30, file=D:\6\node\fablab\node_modules\mongoose\lib\query.js, function=null, line=1794, method=null, native=false, column=16, file=D:\6\node\fablab\node_modules\mongoose\lib\utils.js, function=null, line=414, method=null, native=false, column=5, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js, function=null, line=953, method=null, native=false, column=35, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js, function=null, line=683, method=null, native=false], stack=[TypeError: Cannot read property 'plan' of null,     at D:\6\node\fablab\routes\course_milestone_api.js:179:59,     at Promise.<anonymous> (D:\6\node\fablab\model\student_plan_model.js:101:4),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20),     at D:\6\node\fablab\node_modules\mongoose\lib\query.js:1794:30,     at D:\6\node\fablab\node_modules\mongoose\lib\utils.js:414:16,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\collection.js:953:5,     at D:\6\node\fablab\node_modules\mongoose\node_modules\mongodb\lib\mongodb\cursor.js:683:35]
2013-10-22T12:21:13.951Z - error: uncaughtException: Unexpected token ) date=Tue Oct 22 2013 20:21:13 GMT+0800 (中国标准时间), pid=10128, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=59846656, heapTotal=56172032, heapUsed=31083744, loadavg=[0, 0, 0], uptime=332963.2273213, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=24, file=D:\6\node\fablab\routes\course_milestone_api.js, function=, line=24, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false], stack=[SyntaxError: Unexpected token ),     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (D:\6\node\fablab\routes\course_milestone_api.js:24:24),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32)]
2013-10-22T12:26:18.219Z - error: uncaughtException: doc is not defined date=Tue Oct 22 2013 20:26:18 GMT+0800 (中国标准时间), pid=2548, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=78864384, heapTotal=63359488, heapUsed=36138880, loadavg=[0, 0, 0], uptime=333267.4947244, trace=[column=19, file=D:\6\node\fablab\model\student_plan_model.js, function=, line=110, method=null, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false, column=15, file=D:\6\node\fablab\node_modules\mongoose\lib\promise.js, function=Promise.resolve, line=108, method=resolve, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false, column=20, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.fulfill, line=92, method=fulfill, native=false], stack=[ReferenceError: doc is not defined,     at Promise.<anonymous> (D:\6\node\fablab\model\student_plan_model.js:110:19),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20),     at Promise.resolve (D:\6\node\fablab\node_modules\mongoose\lib\promise.js:108:15),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38),     at Promise.fulfill (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20)]
2013-10-22T13:02:11.292Z - error: uncaughtException: studentAnswerModel is not defined date=Tue Oct 22 2013 21:02:11 GMT+0800 (中国标准时间), pid=6540, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=79028224, heapTotal=63359488, heapUsed=36919944, loadavg=[0, 0, 0], uptime=335420.5678731, trace=[column=8, file=D:\6\node\fablab\routes\course_student_api.js, function=null, line=266, method=null, native=false, column=13, file=D:\6\node\node_modules\async\lib\async.js, function=null, line=229, method=null, native=false, column=25, file=D:\6\node\node_modules\async\lib\async.js, function=null, line=139, method=null, native=false, column=17, file=D:\6\node\node_modules\async\lib\async.js, function=null, line=226, method=null, native=false, column=34, file=D:\6\node\node_modules\async\lib\async.js, function=null, line=553, method=null, native=false, column=21, file=D:\6\node\fablab\routes\course_student_api.js, function=null, line=259, method=null, native=false, column=7, file=D:\6\node\fablab\model\question_model.js, function=, line=81, method=null, native=false, column=8, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=, line=162, method=null, native=false, column=17, file=events.js, function=Promise.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=38, file=D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js, function=Promise.emit, line=79, method=emit, native=false], stack=[ReferenceError: studentAnswerModel is not defined,     at D:\6\node\fablab\routes\course_student_api.js:266:8,     at D:\6\node\node_modules\async\lib\async.js:229:13,     at D:\6\node\node_modules\async\lib\async.js:139:25,     at D:\6\node\node_modules\async\lib\async.js:226:17,     at D:\6\node\node_modules\async\lib\async.js:553:34,     at D:\6\node\fablab\routes\course_student_api.js:259:21,     at Promise.<anonymous> (D:\6\node\fablab\model\question_model.js:81:7),     at Promise.<anonymous> (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8),     at Promise.EventEmitter.emit (events.js:95:17),     at Promise.emit (D:\6\node\fablab\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38)]
2013-10-26T11:51:11.364Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 19:51:11 GMT+0800 (中国标准时间), pid=8828, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=66744320, heapTotal=55140096, heapUsed=32220536, loadavg=[0, 0, 0], uptime=83485.8537849, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-26T11:52:04.028Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 19:52:04 GMT+0800 (中国标准时间), pid=6132, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=66719744, heapTotal=55140096, heapUsed=32220752, loadavg=[0, 0, 0], uptime=83538.5177971, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-26T11:53:51.873Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 19:53:51 GMT+0800 (中国标准时间), pid=7212, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=66588672, heapTotal=55140096, heapUsed=32220568, loadavg=[0, 0, 0], uptime=83646.3619654, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-26T11:55:25.094Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 19:55:25 GMT+0800 (中国标准时间), pid=3044, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=66883584, heapTotal=55140096, heapUsed=32220576, loadavg=[0, 0, 0], uptime=83739.5832974, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-26T11:55:54.506Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 19:55:54 GMT+0800 (中国标准时间), pid=8716, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=66527232, heapTotal=55140096, heapUsed=32220616, loadavg=[0, 0, 0], uptime=83768.9959797, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-26T12:01:49.833Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - read ECONNRESET date=Sat Oct 26 2013 20:01:49 GMT+0800 (中国标准时间), pid=1988, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=68419584, heapTotal=57191936, heapUsed=33505008, loadavg=[0, 0, 0], uptime=84124.3233033, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-26T12:01:49.843Z - error: uncaughtException: Redis connection to localhost:6379 failed - read ECONNRESET date=Sat Oct 26 2013 20:01:49 GMT+0800 (中国标准时间), pid=1988, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=68759552, heapTotal=57191936, heapUsed=33841000, loadavg=[0, 0, 0], uptime=84124.3403042, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-26T12:01:51.114Z - error: uncaughtException: Redis connection to localhost:6379 failed - connect ECONNREFUSED date=Sat Oct 26 2013 20:01:51 GMT+0800 (中国标准时间), pid=1988, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=69013504, heapTotal=57191936, heapUsed=34078416, loadavg=[0, 0, 0], uptime=84125.6073767, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-26T12:01:51.128Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED date=Sat Oct 26 2013 20:01:51 GMT+0800 (中国标准时间), pid=1988, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=69173248, heapTotal=57191936, heapUsed=34236136, loadavg=[0, 0, 0], uptime=84125.6183773, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-26T12:09:30.856Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 20:09:30 GMT+0800 (中国标准时间), pid=5020, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=68599808, heapTotal=57191936, heapUsed=32130464, loadavg=[0, 0, 0], uptime=230.7002038, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-26T12:10:57.359Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 20:10:57 GMT+0800 (中国标准时间), pid=4232, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=67878912, heapTotal=57191936, heapUsed=31994512, loadavg=[0, 0, 0], uptime=317.2179557, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-26T12:11:18.450Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 20:11:18 GMT+0800 (中国标准时间), pid=1376, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=67911680, heapTotal=57191936, heapUsed=31994536, loadavg=[0, 0, 0], uptime=338.3247928, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-26T12:11:42.240Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 20:11:42 GMT+0800 (中国标准时间), pid=5108, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=68173824, heapTotal=57191936, heapUsed=31995160, loadavg=[0, 0, 0], uptime=362.0992345, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-26T12:12:16.311Z - error: uncaughtException: Cannot find module './utils/vm' date=Sat Oct 26 2013 20:12:16 GMT+0800 (中国标准时间), pid=1096, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=67686400, heapTotal=57191936, heapUsed=31814376, loadavg=[0, 0, 0], uptime=396.1852944, trace=[column=15, file=module.js, function=Function.Module._resolveFilename, line=338, method=Module._resolveFilename, native=false, column=25, file=module.js, function=Function.Module._load, line=280, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=7, file=D:\6\node\fablab\routes\vm_api.js, function=, line=13, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false], stack=[Error: Cannot find module './utils/vm',     at Function.Module._resolveFilename (module.js:338:15),     at Function.Module._load (module.js:280:25),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (D:\6\node\fablab\routes\vm_api.js:13:7),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17)]
2013-10-26T12:12:46.824Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 20:12:46 GMT+0800 (中国标准时间), pid=4984, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=68268032, heapTotal=57191936, heapUsed=32067656, loadavg=[0, 0, 0], uptime=426.698948, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=7, file=D:\6\node\fablab\routes\vm_api.js, function=, line=13, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (D:\6\node\fablab\routes\vm_api.js:13:7),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32)]
2013-10-26T12:13:05.591Z - error: uncaughtException: Unexpected token ( date=Sat Oct 26 2013 20:13:05 GMT+0800 (中国标准时间), pid=5044, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=68157440, heapTotal=57191936, heapUsed=32256768, loadavg=[0, 0, 0], uptime=445.465781, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=14, file=D:\6\node\fablab\utils\vm.js, function=, line=11, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false], stack=[SyntaxError: Unexpected token (,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at Object.<anonymous> (D:\6\node\fablab\utils\vm.js:11:14),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32)]
2013-10-26T16:34:28.133Z - error: uncaughtException: ENOENT, unlink 'D:\6\node\fablab\public\uploads\ae2f2fd59ebad03a0f7de54543dd82a2.png' date=Sun Oct 27 2013 00:34:28 GMT+0800 (中国标准时间), pid=5576, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=71340032, heapTotal=58211840, heapUsed=34789368, loadavg=[0, 0, 0], uptime=11643.4974861, trace=[], stack=[Error: ENOENT, unlink 'D:\6\node\fablab\public\uploads\ae2f2fd59ebad03a0f7de54543dd82a2.png']
2013-10-26T16:36:28.313Z - error: uncaughtException: ENOENT, unlink 'D:\6\node\fablab\public\uploads\79a27ab1f9380a54f07aff1cc29850a0.png' date=Sun Oct 27 2013 00:36:28 GMT+0800 (中国标准时间), pid=5576, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=73068544, heapTotal=58211840, heapUsed=35772928, loadavg=[0, 0, 0], uptime=11763.6783601, trace=[], stack=[Error: ENOENT, unlink 'D:\6\node\fablab\public\uploads\79a27ab1f9380a54f07aff1cc29850a0.png']
2013-10-26T16:38:45.599Z - error: uncaughtException: ENOENT, unlink 'D:\6\node\fablab\public\uploads\c0680ed0c477f260e08826cb649899a8.png' date=Sun Oct 27 2013 00:38:45 GMT+0800 (中国标准时间), pid=4768, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=78491648, heapTotal=61307648, heapUsed=29717288, loadavg=[0, 0, 0], uptime=11900.9652124, trace=[], stack=[Error: ENOENT, unlink 'D:\6\node\fablab\public\uploads\c0680ed0c477f260e08826cb649899a8.png']
2013-10-27T14:01:21.429Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:01:21 GMT+0800 (中国标准时间), pid=1268, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=78491648, heapTotal=61307648, heapUsed=38336424, loadavg=[0, 0, 0], uptime=39567.4076424, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:02:45.203Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:02:45 GMT+0800 (中国标准时间), pid=5752, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77398016, heapTotal=61307648, heapUsed=28713872, loadavg=[0, 0, 0], uptime=39651.181434, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:04:02.328Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:04:02 GMT+0800 (中国标准时间), pid=5400, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77500416, heapTotal=61307648, heapUsed=28266904, loadavg=[0, 0, 0], uptime=39728.3108456, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:04:21.031Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:04:21 GMT+0800 (中国标准时间), pid=2376, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76877824, heapTotal=61307648, heapUsed=28387840, loadavg=[0, 0, 0], uptime=39747.0099151, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:05:15.921Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:05:15 GMT+0800 (中国标准时间), pid=7084, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77377536, heapTotal=61307648, heapUsed=28571272, loadavg=[0, 0, 0], uptime=39801.8970545, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:23:07.084Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:23:07 GMT+0800 (中国标准时间), pid=4324, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76910592, heapTotal=61307648, heapUsed=28687456, loadavg=[0, 0, 0], uptime=40873.0623216, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:27:27.479Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:27:27 GMT+0800 (中国标准时间), pid=3436, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77447168, heapTotal=61307648, heapUsed=27658744, loadavg=[0, 0, 0], uptime=41133.4552152, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:32:59.148Z - error: uncaughtException: err is not defined date=Sun Oct 27 2013 22:32:59 GMT+0800 (中国标准时间), pid=6776, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77705216, heapTotal=61307648, heapUsed=32756800, loadavg=[0, 0, 0], uptime=41465.1301859, trace=[column=12, file=D:\6\node\fablab\routes\vm_api.js, function=null, line=26, method=null, native=false, column=19, file=[as oncomplete] (fs.js, function=Object.cb, line=154, method=cb, native=false], stack=[ReferenceError: err is not defined,     at D:\6\node\fablab\routes\vm_api.js:26:12,     at Object.cb [as oncomplete] (fs.js:154:19)]
2013-10-27T14:32:59.185Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:32:59 GMT+0800 (中国标准时间), pid=6776, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77946880, heapTotal=61307648, heapUsed=33150272, loadavg=[0, 0, 0], uptime=41465.1631878, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:34:28.324Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:34:28 GMT+0800 (中国标准时间), pid=5788, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77197312, heapTotal=61307648, heapUsed=27672616, loadavg=[0, 0, 0], uptime=41554.2992861, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:45:29.783Z - error: uncaughtException: write after end date=Sun Oct 27 2013 22:45:29 GMT+0800 (中国标准时间), pid=6980, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77746176, heapTotal=61307648, heapUsed=32867640, loadavg=[0, 0, 0], uptime=42215.7581194, trace=[column=12, file=_stream_writable.js, function=writeAfterEnd, line=125, method=null, native=false, column=5, file=_stream_writable.js, function=Gzip.Writable.write, line=170, method=Writable.write, native=false, column=18, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.write, line=81, method=res.write, native=false, column=23, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js, function=ServerResponse.res.end, line=86, method=res.end, native=false, column=13, file=D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js, function=null, line=282, method=null, native=false, column=18, file=D:\6\node\node_modules\connect-redis\lib\connect-redis.js, function=null, line=130, method=null, native=false, column=9, file=D:\6\node\node_modules\redis\index.js, function=try_callback, line=532, method=null, native=false, column=13, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.return_reply, line=614, method=return_reply, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=266, method=null, native=false, column=17, file=events.js, function=ReplyParser.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false], stack=[Error: write after end,     at writeAfterEnd (_stream_writable.js:125:12),     at Gzip.Writable.write (_stream_writable.js:170:5),     at ServerResponse.res.write (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:81:18),     at ServerResponse.res.end (D:\6\node\node_modules\express\node_modules\connect\lib\middleware\compress.js:86:23),     at D:\6\node\node_modules\express\node_modules\connect\lib\middleware\session.js:282:13,     at D:\6\node\node_modules\connect-redis\lib\connect-redis.js:130:18,     at try_callback (D:\6\node\node_modules\redis\index.js:532:9),     at RedisClient.return_reply (D:\6\node\node_modules\redis\index.js:614:13),     at ReplyParser.<anonymous> (D:\6\node\node_modules\redis\index.js:266:14),     at ReplyParser.EventEmitter.emit (events.js:95:17)]
2013-10-27T14:45:54.867Z - error: uncaughtException: Can't set headers after they are sent. date=Sun Oct 27 2013 22:45:54 GMT+0800 (中国标准时间), pid=5236, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77320192, heapTotal=61307648, heapUsed=27685312, loadavg=[0, 0, 0], uptime=42240.8105523, trace=[column=11, file=http.js, function=ServerResponse.OutgoingMessage.setHeader, line=708, method=OutgoingMessage.setHeader, native=false, column=22, file=D:\6\node\node_modules\express\node_modules\connect\lib\patch.js, function=ServerResponse.res.setHeader, line=59, method=res.setHeader, native=false, column=10, file=D:\6\node\node_modules\express\lib\response.js, function=ServerResponse.res.set.res.header, line=518, method=res.set.res.header, native=false, column=8, file=D:\6\node\node_modules\express\lib\response.js, function=ServerResponse.res.location, line=649, method=res.location, native=false, column=8, file=D:\6\node\node_modules\express\lib\response.js, function=ServerResponse.res.redirect, line=691, method=res.redirect, native=false, column=27, file=D:\6\node\fablab\routes\vm_api.js, function=null, line=29, method=null, native=false, column=15, file=fs.js, function=Object.oncomplete, line=93, method=oncomplete, native=false], stack=[Error: Can't set headers after they are sent.,     at ServerResponse.OutgoingMessage.setHeader (http.js:708:11),     at ServerResponse.res.setHeader (D:\6\node\node_modules\express\node_modules\connect\lib\patch.js:59:22),     at ServerResponse.res.set.res.header (D:\6\node\node_modules\express\lib\response.js:518:10),     at ServerResponse.res.location (D:\6\node\node_modules\express\lib\response.js:649:8),     at ServerResponse.res.redirect (D:\6\node\node_modules\express\lib\response.js:691:8),     at D:\6\node\fablab\routes\vm_api.js:29:27,     at Object.oncomplete (fs.js:93:15)]
2013-10-27T14:49:02.512Z - error: uncaughtException: Can't set headers after they are sent. date=Sun Oct 27 2013 22:49:02 GMT+0800 (中国标准时间), pid=4436, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=77701120, heapTotal=61307648, heapUsed=32617120, loadavg=[0, 0, 0], uptime=42428.4882869, trace=[column=11, file=http.js, function=ServerResponse.OutgoingMessage.setHeader, line=708, method=OutgoingMessage.setHeader, native=false, column=22, file=D:\6\node\node_modules\express\node_modules\connect\lib\patch.js, function=ServerResponse.res.setHeader, line=59, method=res.setHeader, native=false, column=10, file=D:\6\node\node_modules\express\lib\response.js, function=ServerResponse.res.set.res.header, line=518, method=res.set.res.header, native=false, column=8, file=D:\6\node\node_modules\express\lib\response.js, function=ServerResponse.res.location, line=649, method=res.location, native=false, column=8, file=D:\6\node\node_modules\express\lib\response.js, function=ServerResponse.res.redirect, line=691, method=res.redirect, native=false, column=27, file=D:\6\node\fablab\routes\vm_api.js, function=null, line=30, method=null, native=false, column=15, file=fs.js, function=Object.oncomplete, line=93, method=oncomplete, native=false], stack=[Error: Can't set headers after they are sent.,     at ServerResponse.OutgoingMessage.setHeader (http.js:708:11),     at ServerResponse.res.setHeader (D:\6\node\node_modules\express\node_modules\connect\lib\patch.js:59:22),     at ServerResponse.res.set.res.header (D:\6\node\node_modules\express\lib\response.js:518:10),     at ServerResponse.res.location (D:\6\node\node_modules\express\lib\response.js:649:8),     at ServerResponse.res.redirect (D:\6\node\node_modules\express\lib\response.js:691:8),     at D:\6\node\fablab\routes\vm_api.js:30:27,     at Object.oncomplete (fs.js:93:15)]
2013-10-27T15:44:48.258Z - error: uncaughtException: Unknown encoding: text date=Sun Oct 27 2013 23:44:48 GMT+0800 (中国标准时间), pid=2428, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=78528512, heapTotal=61307648, heapUsed=29270088, loadavg=[0, 0, 0], uptime=45774.2396529, trace=[column=11, file=fs.js, function=assertEncoding, line=99, method=null, native=false, column=3, file=fs.js, function=Object.fs.readFile, line=182, method=fs.readFile, native=false, column=7, file=D:\6\node\fablab\routes\vm_api.js, function=null, line=73, method=null, native=false, column=15, file=fs.js, function=Object.oncomplete, line=93, method=oncomplete, native=false], stack=[Error: Unknown encoding: text,     at assertEncoding (fs.js:99:11),     at Object.fs.readFile (fs.js:182:3),     at D:\6\node\fablab\routes\vm_api.js:73:7,     at Object.oncomplete (fs.js:93:15)]
2013-10-27T16:08:08.602Z - error: uncaughtException: ENOENT, readdir 'D:\6\node\fablab\routes\routes' date=Mon Oct 28 2013 00:08:08 GMT+0800 (中国标准时间), pid=3720, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=73719808, heapTotal=58211840, heapUsed=36969832, loadavg=[0, 0, 0], uptime=47174.5857481, trace=[], stack=[Error: ENOENT, readdir 'D:\6\node\fablab\routes\routes']
2013-10-27T16:38:51.314Z - error: uncaughtException: callback is not defined date=Mon Oct 28 2013 00:38:51 GMT+0800 (中国标准时间), pid=1268, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=74158080, heapTotal=58211840, heapUsed=37395192, loadavg=[0, 0, 0], uptime=49017.2881447, trace=[column=8, file=D:\6\node\fablab\routes\vm_api.js, function=null, line=54, method=null, native=false, column=14, file=fs.js, function=null, line=252, method=null, native=false, column=15, file=fs.js, function=Object.oncomplete, line=93, method=oncomplete, native=false], stack=[ReferenceError: callback is not defined,     at D:\6\node\fablab\routes\vm_api.js:54:8,     at fs.js:252:14,     at Object.oncomplete (fs.js:93:15)]
2013-10-29T12:54:50.762Z - error: uncaughtException: mqtt is not defined date=Tue Oct 29 2013 20:54:50 GMT+0800 (中国标准时间), pid=6892, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=61874176, heapTotal=56172032, heapUsed=33136024, loadavg=[0, 0, 0], uptime=5706.6347298, trace=[column=14, file=D:\6\node\fablab\routes\mqtt_api.js, function=, line=9, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true], stack=[ReferenceError: mqtt is not defined,     at Object.<anonymous> (D:\6\node\fablab\routes\mqtt_api.js:9:14),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native)]
2013-10-29T12:56:52.971Z - error: uncaughtException: mqtt is not defined date=Tue Oct 29 2013 20:56:52 GMT+0800 (中国标准时间), pid=6868, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=61726720, heapTotal=56172032, heapUsed=33136024, loadavg=[0, 0, 0], uptime=5828.84872, trace=[column=14, file=D:\6\node\fablab\routes\mqtt_api.js, function=, line=9, method=null, native=false, column=26, file=module.js, function=Module._compile, line=456, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true], stack=[ReferenceError: mqtt is not defined,     at Object.<anonymous> (D:\6\node\fablab\routes\mqtt_api.js:9:14),     at Module._compile (module.js:456:26),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native)]
2013-10-29T16:28:28.221Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - read ECONNRESET date=Wed Oct 30 2013 00:28:28 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=71495680, heapTotal=57191936, heapUsed=35201840, loadavg=[0, 0, 0], uptime=13277.2957468, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:28.244Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET date=Wed Oct 30 2013 00:28:28 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=71868416, heapTotal=57191936, heapUsed=35541560, loadavg=[0, 0, 0], uptime=13277.3257485, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:28.261Z - error: uncaughtException: Redis connection to localhost:6379 failed - read ECONNRESET date=Wed Oct 30 2013 00:28:28 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=72032256, heapTotal=57191936, heapUsed=35711288, loadavg=[0, 0, 0], uptime=13277.3417495, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:28.277Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET date=Wed Oct 30 2013 00:28:28 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=72183808, heapTotal=57191936, heapUsed=35862424, loadavg=[0, 0, 0], uptime=13277.3587504, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:28.295Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET date=Wed Oct 30 2013 00:28:28 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=72339456, heapTotal=57191936, heapUsed=36023344, loadavg=[0, 0, 0], uptime=13277.3757514, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:29.511Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:29 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=72646656, heapTotal=58211840, heapUsed=36321696, loadavg=[0, 0, 0], uptime=13278.5848206, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:29.578Z - error: uncaughtException: Redis connection to localhost:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:29 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=72810496, heapTotal=58211840, heapUsed=36491904, loadavg=[0, 0, 0], uptime=13278.6558246, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:29.597Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:29 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=72966144, heapTotal=58211840, heapUsed=36650656, loadavg=[0, 0, 0], uptime=13278.6788259, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:29.619Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:29 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=73117696, heapTotal=58211840, heapUsed=36803392, loadavg=[0, 0, 0], uptime=13278.6918267, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:29.640Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:29 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=73269248, heapTotal=58211840, heapUsed=36963376, loadavg=[0, 0, 0], uptime=13278.7138279, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:30.976Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:30 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=73453568, heapTotal=58211840, heapUsed=37148056, loadavg=[0, 0, 0], uptime=13280.0569048, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:31.038Z - error: uncaughtException: Redis connection to localhost:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:31 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=73687040, heapTotal=58211840, heapUsed=37311672, loadavg=[0, 0, 0], uptime=13280.1069076, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:31.087Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:31 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=73850880, heapTotal=58211840, heapUsed=37478200, loadavg=[0, 0, 0], uptime=13280.1679111, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:31.107Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:31 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=74063872, heapTotal=58211840, heapUsed=37676384, loadavg=[0, 0, 0], uptime=13280.1889123, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:31.119Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:31 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=74227712, heapTotal=58211840, heapUsed=37831144, loadavg=[0, 0, 0], uptime=13280.2019131, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:32.759Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:32 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=74276864, heapTotal=58211840, heapUsed=38011912, loadavg=[0, 0, 0], uptime=13281.8200056, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:32.806Z - error: uncaughtException: Redis connection to localhost:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:32 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76574720, heapTotal=61307648, heapUsed=27954840, loadavg=[0, 0, 0], uptime=13281.880009, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:32.839Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:32 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76668928, heapTotal=61307648, heapUsed=28201928, loadavg=[0, 0, 0], uptime=13281.9210114, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:32.868Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:32 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76685312, heapTotal=61307648, heapUsed=28355792, loadavg=[0, 0, 0], uptime=13281.950013, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:32.885Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:32 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76660736, heapTotal=61307648, heapUsed=28533928, loadavg=[0, 0, 0], uptime=13281.967014, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:35.034Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:35 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76697600, heapTotal=61307648, heapUsed=28713224, loadavg=[0, 0, 0], uptime=13284.1141368, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:35.082Z - error: uncaughtException: Redis connection to localhost:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:35 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76615680, heapTotal=61307648, heapUsed=28893000, loadavg=[0, 0, 0], uptime=13284.1631396, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:35.116Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:35 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76673024, heapTotal=61307648, heapUsed=29082176, loadavg=[0, 0, 0], uptime=13284.1971416, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:35.144Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:35 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76767232, heapTotal=61307648, heapUsed=29252488, loadavg=[0, 0, 0], uptime=13284.2241431, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:35.158Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:35 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76783616, heapTotal=61307648, heapUsed=29402744, loadavg=[0, 0, 0], uptime=13284.239144, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:38.183Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:38 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76849152, heapTotal=61307648, heapUsed=29592880, loadavg=[0, 0, 0], uptime=13287.2633169, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:38.236Z - error: uncaughtException: Redis connection to localhost:6379 failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:38 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76869632, heapTotal=61307648, heapUsed=29744408, loadavg=[0, 0, 0], uptime=13287.31632, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:38.259Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:38 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76914688, heapTotal=61307648, heapUsed=29906824, loadavg=[0, 0, 0], uptime=13287.3413214, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:38.294Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:38 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76922880, heapTotal=61307648, heapUsed=30056624, loadavg=[0, 0, 0], uptime=13287.3743233, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-29T16:28:38.317Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Wed Oct 30 2013 00:28:38 GMT+0800 (中国标准时间), pid=2992, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=76857344, heapTotal=61307648, heapUsed=30228288, loadavg=[0, 0, 0], uptime=13287.3993247, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-10-31T08:12:39.354Z - error: uncaughtException: Unexpected identifier date=Thu Oct 31 2013 16:12:39 GMT+0800 (中国标准时间), pid=3672, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=61894656, heapTotal=56172032, heapUsed=33081464, loadavg=[0, 0, 0], uptime=552.2127215, trace=[column=25, file=module.js, function=Module._compile, line=439, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=474, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=356, method=load, native=false, column=12, file=module.js, function=Function.Module._load, line=312, method=Module._load, native=false, column=17, file=module.js, function=Module.require, line=364, method=require, native=false, column=17, file=module.js, function=require, line=380, method=null, native=false, column=2, file=D:\6\node\fablab\app.js, function=bootController, line=688, method=null, native=false, column=5, file=D:\6\node\fablab\app.js, function=null, line=680, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=true, column=9, file=D:\6\node\fablab\app.js, function=null, line=673, method=null, native=false], stack=[SyntaxError: Unexpected identifier,     at Module._compile (module.js:439:25),     at Object.Module._extensions..js (module.js:474:10),     at Module.load (module.js:356:32),     at Function.Module._load (module.js:312:12),     at Module.require (module.js:364:17),     at require (module.js:380:17),     at bootController (D:\6\node\fablab\app.js:688:2),     at D:\6\node\fablab\app.js:680:5,     at Array.forEach (native),     at D:\6\node\fablab\app.js:673:9]
2013-10-31T08:20:53.533Z - error: uncaughtException: listen EADDRINUSE date=Thu Oct 31 2013 16:20:53 GMT+0800 (中国标准时间), pid=472, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[NODE, D:\6\node\fablab\APP], rss=48537600, heapTotal=33203200, heapUsed=21563248, loadavg=[0, 0, 0], uptime=1046.3840608, trace=[column=11, file=net.js, function=errnoException, line=863, method=null, native=false, column=14, file=net.js, function=Server._listen2, line=1008, method=_listen2, native=false, column=10, file=net.js, function=listen, line=1030, method=null, native=false, column=9, file=net.js, function=null, line=1104, method=null, native=false, column=18, file=dns.js, function=null, line=72, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false, column=11, file=module.js, function=Function.Module.runMain, line=499, method=Module.runMain, native=false, column=16, file=node.js, function=startup, line=119, method=null, native=false, column=3, file=node.js, function=null, line=903, method=null, native=false], stack=[Error: listen EADDRINUSE,     at errnoException (net.js:863:11),     at Server._listen2 (net.js:1008:14),     at listen (net.js:1030:10),     at net.js:1104:9,     at dns.js:72:18,     at process._tickDomainCallback (node.js:459:13),     at Function.Module.runMain (module.js:499:11),     at startup (node.js:119:16),     at node.js:903:3]
2013-11-01T16:29:03.340Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - read ECONNRESET date=Sat Nov 02 2013 00:29:03 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=65830912, heapTotal=72646912, heapUsed=42578176, loadavg=[0, 0, 0], uptime=66364.7392264, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:03.348Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET date=Sat Nov 02 2013 00:29:03 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=67268608, heapTotal=72646912, heapUsed=42936360, loadavg=[0, 0, 0], uptime=66364.7502271, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:03.352Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET date=Sat Nov 02 2013 00:29:03 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=67469312, heapTotal=72646912, heapUsed=43098864, loadavg=[0, 0, 0], uptime=66364.7542273, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:03.357Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET date=Sat Nov 02 2013 00:29:03 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=67715072, heapTotal=72646912, heapUsed=43263328, loadavg=[0, 0, 0], uptime=66364.7592276, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:03.361Z - error: uncaughtException: Redis connection to localhost:6379 failed - read ECONNRESET date=Sat Nov 02 2013 00:29:03 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=67956736, heapTotal=72646912, heapUsed=43450920, loadavg=[0, 0, 0], uptime=66364.7642279, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - read ECONNRESET,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:04.617Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:04 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=68628480, heapTotal=72646912, heapUsed=43761880, loadavg=[0, 0, 0], uptime=66366.0182996, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:04.651Z - error: uncaughtException: Redis connection to localhost:6379 failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:04 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=68841472, heapTotal=72646912, heapUsed=43942568, loadavg=[0, 0, 0], uptime=66366.0473013, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:04.669Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:04 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=68988928, heapTotal=72646912, heapUsed=44104432, loadavg=[0, 0, 0], uptime=66366.0693025, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:04.691Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:04 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=69156864, heapTotal=72646912, heapUsed=44254992, loadavg=[0, 0, 0], uptime=66366.0843034, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:04.706Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:04 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=69226496, heapTotal=72646912, heapUsed=44405392, loadavg=[0, 0, 0], uptime=66366.1003043, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:06.067Z - error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:06 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=69353472, heapTotal=72646912, heapUsed=44613672, loadavg=[0, 0, 0], uptime=66367.4673825, trace=[column=24, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=RedisClient.on_error, line=140, method=on_error, native=false, column=14, file=D:\6\node\node_modules\kue\node_modules\redis\index.js, function=, line=74, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\kue\node_modules\redis\index.js:140:24),     at Socket.<anonymous> (D:\6\node\node_modules\kue\node_modules\redis\index.js:74:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:06.108Z - error: uncaughtException: Redis connection to localhost:6379 failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:06 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=69443584, heapTotal=72646912, heapUsed=44775552, loadavg=[0, 0, 0], uptime=66367.5093849, trace=[column=24, file=D:\6\node\node_modules\redis\index.js, function=RedisClient.on_error, line=151, method=on_error, native=false, column=14, file=D:\6\node\node_modules\redis\index.js, function=, line=86, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\redis\index.js:151:24),     at Socket.<anonymous> (D:\6\node\node_modules\redis\index.js:86:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:06.147Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:06 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=69505024, heapTotal=72646912, heapUsed=44929888, loadavg=[0, 0, 0], uptime=66367.5483871, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:06.155Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:06 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=69664768, heapTotal=72646912, heapUsed=45094096, loadavg=[0, 0, 0], uptime=66367.5563876, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
2013-11-01T16:29:06.165Z - error: uncaughtException: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED date=Sat Nov 02 2013 00:29:06 GMT+0800 (中国标准时间), pid=2328, uid=null, gid=null, cwd=D:\6\node\fablab, execPath=D:\Program Files\StrongLoop Node\node.exe, version=v0.10.0, argv=[node, D:\6\node\fablab\app], rss=69906432, heapTotal=72646912, heapUsed=45242712, loadavg=[0, 0, 0], uptime=66367.564388, trace=[column=24, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=RedisClient.on_error, line=149, method=on_error, native=false, column=14, file=D:\6\node\node_modules\socket.io\node_modules\redis\index.js, function=, line=83, method=null, native=false, column=17, file=events.js, function=Socket.EventEmitter.emit, line=95, method=EventEmitter.emit, native=false, column=14, file=net.js, function=null, line=411, method=null, native=false, column=13, file=node.js, function=process._tickDomainCallback, line=459, method=_tickDomainCallback, native=false], stack=[Error: Redis connection to 127.0.0.1:[object Object] failed - connect ECONNREFUSED,     at RedisClient.on_error (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:149:24),     at Socket.<anonymous> (D:\6\node\node_modules\socket.io\node_modules\redis\index.js:83:14),     at Socket.EventEmitter.emit (events.js:95:17),     at net.js:411:14,     at process._tickDomainCallback (node.js:459:13)]
